"""Low-dependency runtime error contracts shared by ontology resolution and execution."""
from enum import StrEnum


class ExecutionErrorCode(StrEnum):
    INVALID_EXECUTION_PLAN = "INVALID_EXECUTION_PLAN"
    MISSING_EXECUTION_MAPPING = "MISSING_EXECUTION_MAPPING"
    MISSING_RUNTIME_BINDING = "MISSING_RUNTIME_BINDING"
    UNPUBLISHED_RUNTIME_BINDING = "UNPUBLISHED_RUNTIME_BINDING"
    UNSUPPORTED_RUNTIME_CAPABILITY = "UNSUPPORTED_RUNTIME_CAPABILITY"
    RUNTIME_BACKEND_MISMATCH = "RUNTIME_BACKEND_MISMATCH"
    UNRESOLVED_TIME_SCOPE = "UNRESOLVED_TIME_SCOPE"
    UNSUPPORTED_COMPARISON = "UNSUPPORTED_COMPARISON"
    SUPERSONIC_TIMEOUT = "SUPERSONIC_TIMEOUT"
    SUPERSONIC_NETWORK_ERROR = "SUPERSONIC_NETWORK_ERROR"
    SUPERSONIC_QUERY_ERROR = "SUPERSONIC_QUERY_ERROR"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    DEPENDENCY_FAILED = "DEPENDENCY_FAILED"
